export const appConfig = {
  //api_ur: 'http://178.62.47.125/api/v1/',
  api_ur: 'https://api.mpositive.co.uk/api/v1/',
  auth_url: 'authenticate',
  register_url: 'register',
  user_info_url: 'me',
  reset_pass_url: 'customer/forgot/request',
  categories_url: 'categories',
  products_url: 'products',
  category_url: 'category',
  product_url: 'product',
  payments_url: 'payment-types',
  payment_url: 'payment',
  sync_url: 'syncs',
  refund_url: 'refund',
  defaultCurrency: '£',
};